spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 15